name: PNPM Install with Cache
description: Setup pnpm and install dependencies, caches node_modules
runs:
  using: composite
  steps:
    - uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: actions/setup-node@v3
      with:
        node-version: "lts/*"
        cache: "pnpm"
    - shell: bash
      run: pnpm install --frozen-lockfile
